### ISSUE TITLE
Transactions fail

### ISSUE THREAD

**Issue by electricjones** [PommeVerte/docker-gremlin-server#2]
Transactions fail against this container. My suspicion is that the container must have an installation of neo4j or something similar to enable transactions.

**Comment by dmill-bz** [comment]
ah yes that's possible. From memory I think neo4j is installed just not available through the configuration. You would need to change the configuration file. 
I haven't documented the process yet but you can find some info in this ticket : https://github.com/jbmusso/gremlin-javascript/issues/40
There's one post by me and one by the person I'm talking to, for configuration.

**Comment by electricjones** [comment]
I overrode the `gremlin-server.yml` file with the `gremlin-server-spider.yml` file you provided (using volumes in the docker-compose) and came up with the following error for each gremlin test. The original test only fails on the transaction test.

```
Brightzone\GremlinDriver\ServerException: The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : No such property: g for class: Script1 >
```

I am sure it's a configuration, but I don't know what conig is wrong. Could you take a look?

**Comment by dmill-bz** [comment]
hmm I'll have a look
